import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { sassPlugin } from "esbuild-sass-plugin";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const mode = process.argv[2] || "production";

const buildConfigs = {
	development: {
		sourcemap: "inline",
		minify: true,
		drop: [],
		watch: false,
	},
	production: {
		sourcemap: "inline",
		minify: true,
		drop: ['console'],
		watch: false,
	},
};

const config = buildConfigs[mode] || buildConfigs.production;

const context = await esbuild.context({
	plugins: [sassPlugin()],
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: config.sourcemap,
	treeShaking: true,
	outfile: "main.js",
	minify: config.minify,
	drop: config.drop,
	loader: {
		".ts": "ts",
	},
});

if (config.watch) {
	await context.watch();
} else {
	await context.rebuild();
	process.exit(0);
}
